import React,{useState,useEffect,useCallback,useMemo}from'react';
import{motion,AnimatePresence}from'framer-motion';
import{Users,Crown,Search,Filter,Download,FileText,Printer,ChevronDown,ChevronUp,User,Shield,AlertTriangle,X}from'lucide-react';
import{supabase}from'@/lib/customSupabaseClient';
import{useToast}from'@/components/ui/use-toast';
import{Card,CardHeader,CardTitle,CardContent,CardFooter}from'@/components/ui/card';
import{Input}from'@/components/ui/input';
import{Button}from'@/components/ui/button';
import{Select,SelectContent,SelectItem,SelectTrigger,SelectValue}from'@/components/ui/select';
import{Badge}from'@/components/ui/badge';
import{Dialog,DialogContent,DialogHeader,DialogTitle,DialogFooter}from'@/components/ui/dialog';
import{exportToExcel}from'@/lib/ExportUtils';
import{Helmet}from'react-helmet';
import jsPDF from'jspdf';
import autoTable from'jspdf-autotable';

const GOLD='hsl(var(--neon-igreja))';
const ini=n=>{if(!n)return'D';const p=String(n).trim().split(/\s+/);return(p.length===1?p[0].slice(0,2):`${p[0][0]}${p.at(-1)[0]}`).toUpperCase()};
const funcs=(m,l)=>{const x=m?.funcoes_multiplas;let ids=Array.isArray(x)?x:Array.isArray(x?.funcoes_ids)?x.funcoes_ids:[];if(ids.length){const n=ids.map(id=>l.find(f=>String(f.id)===String(id))?.nome_funcao).filter(Boolean);if(n.length)return n.join(', ')}if(m?.funcoes_exercidas)return String(m.funcoes_exercidas);if(Array.isArray(m?.igreja_funcoes)){const n=m.igreja_funcoes.map(f=>f.nome_funcao).filter(Boolean);if(n.length)return n.join(', ')}return m?.igreja_funcoes?.nome_funcao||'-'};
const dirIds=m=>{const x=m?.dirige_conjuntos_multiplos;if(Array.isArray(x?.conjuntos_ids)&&x.conjuntos_ids.length)return x.conjuntos_ids;if(Array.isArray(x)&&x.length)return x;if(m?.dirige_conjunto_id)return[m.dirige_conjunto_id];return[]};

export default function ConsultaDirigentesConjunto(){
 const{toast}=useToast();
 const[conjuntos,setConjuntos]=useState([]),[all,setAll]=useState([]),[funcoes,setFuncoes]=useState([]),[loading,setLoading]=useState(true),[status,setStatus]=useState('ATIVO'),[conjunto,setConjunto]=useState('todos'),[search,setSearch]=useState(''),[filtros,setFiltros]=useState(true),[selected,setSelected]=useState(null);

 const load=useCallback(async()=>{setLoading(true);try{const[a,b,c]=await Promise.all([
  supabase.from('igreja_conjuntos').select('*').order('nome_conjunto',{ascending:true}),
  supabase.from('igreja_membros').select(`*,conjunto:igreja_conjuntos!igreja_membros_conjunto_id_fkey(nome_conjunto),dirige_conjunto:igreja_conjuntos!igreja_membros_dirige_conjunto_id_fkey(nome_conjunto),cargo:cargos_igreja(nome_cargo),igreja_classes(nome_classe),igreja_funcoes(nome_funcao)`).eq('is_dirigente',true).order('nome_completo',{ascending:true}),
  supabase.from('igreja_funcoes').select('*').order('nome_funcao',{ascending:true})
 ]);if(a.error)throw a.error;if(b.error)throw b.error;if(c.error)throw c.error;setConjuntos(a.data||[]);setAll(b.data||[]);setFuncoes(c.data||[])}catch(e){toast({title:'Erro ao buscar dados',description:e.message,variant:'destructive'})}finally{setLoading(false)}},[toast]);
 useEffect(()=>{load()},[load]);

 const people=useMemo(()=>{const t=search.trim().toLowerCase();return all.filter(m=>{const ids=dirIds(m),names=ids.map(id=>conjuntos.find(c=>String(c.id)===String(id))?.nome_conjunto).filter(Boolean);return(status==='todos'||(m.status||'ATIVO')===status)&&(conjunto==='todos'||ids.some(id=>String(id)===String(conjunto)))&&(!t||`${m.nome_completo||''} ${m.cargo?.nome_cargo||''} ${funcs(m,funcoes)} ${names.join(' ')}`.toLowerCase().includes(t))})},[all,conjuntos,funcoes,status,conjunto,search]);
 const grouped=useMemo(()=>conjuntos.map(c=>({...c,dirigentes:people.filter(m=>dirIds(m).some(id=>String(id)===String(c.id)))})).filter(c=>c.dirigentes.length),[conjuntos,people]);
 const ativos=people.filter(m=>(m.status||'ATIVO')==='ATIVO').length,vinculos=grouped.reduce((n,c)=>n+c.dirigentes.length,0);

 const excel=()=>{const rows=grouped.flatMap(c=>c.dirigentes.map(m=>({Conjunto:c.nome_conjunto,Dirigente:m.nome_completo,'Função/Cargo':m.cargo?.nome_cargo||funcs(m,funcoes),Status:m.status||'ATIVO'})));if(!rows.length)return toast({title:'Sem dados',description:'Não há dirigentes.',variant:'destructive'});exportToExcel(rows,'Dirigentes_por_Conjunto','Dirigentes')};
 const pdf=()=>{if(!people.length)return toast({title:'Sem dados',description:'Não há dirigentes.',variant:'destructive'});const d=new jsPDF('p','mm','a4');d.setFillColor(15,23,42);d.rect(0,0,210,28,'F');d.setTextColor(255,255,255);d.setFont('helvetica','bold');d.setFontSize(12);d.text('IGREJA ASSEMBLEIA DE DEUS',105,10,{align:'center'});d.setFontSize(8);d.text('MINISTÉRIO PLANTAR • LEROLÂNDIA',105,16,{align:'center'});d.setFillColor(234,179,8);d.roundedRect(58,20,94,6,2,2,'F');d.setTextColor(15,23,42);d.setFontSize(7);d.text('DIRIGENTES POR CONJUNTO',105,24.2,{align:'center'});let y=35;grouped.forEach(c=>{d.setFillColor(15,23,42);d.roundedRect(10,y,190,8,2,2,'F');d.setTextColor(255,255,255);d.text(c.nome_conjunto,14,y+5.5);y+=10;autoTable(d,{head:[['DIRIGENTE','FUNÇÃO/CARGO','STATUS']],body:c.dirigentes.map(m=>[m.nome_completo||'-',m.cargo?.nome_cargo||funcs(m,funcoes),m.status||'ATIVO']),startY:y,theme:'grid',styles:{fontSize:7,cellPadding:2},headStyles:{fillColor:[37,99,235]}});y=(d.lastAutoTable?.finalY||y)+7;if(y>260){d.addPage();y=18}});d.save('Dirigentes_por_Conjunto.pdf')};
 const imprimir=()=>{if(!people.length)return toast({title:'Sem dados',description:'Não há dirigentes.',variant:'destructive'});const w=window.open('','_blank');if(!w)return toast({title:'Impressão bloqueada',description:'Permita pop-ups.',variant:'destructive'});w.document.write(`<html><head><title>Dirigentes por Conjunto</title><style>body{font-family:Arial;margin:20px}h1{text-align:center}h2{background:#eab308;padding:7px;text-align:center}.g{margin:15px 0}.gh{background:#0f172a;color:#fff;padding:7px;font-weight:bold}table{width:100%;border-collapse:collapse;font-size:9px}th{background:#2563eb;color:#fff}th,td{border:1px solid #ccc;padding:5px}</style></head><body><h1>IGREJA ASSEMBLEIA DE DEUS MINISTÉRIO PLANTAR</h1><h2>DIRIGENTES POR CONJUNTO</h2>${grouped.map(c=>`<div class="g"><div class="gh">${c.nome_conjunto} (${c.dirigentes.length})</div><table><tr><th>DIRIGENTE</th><th>FUNÇÃO/CARGO</th><th>STATUS</th></tr>${c.dirigentes.map(m=>`<tr><td>${m.nome_completo||'-'}</td><td>${m.cargo?.nome_cargo||funcs(m,funcoes)}</td><td>${m.status||'ATIVO'}</td></tr>`).join('')}</table></div>`).join('')}<script>window.onload=()=>setTimeout(()=>window.print(),150)<\/script></body></html>`);w.document.close()};

 return <div className="dark-igreja text-foreground h-full flex flex-col"><Helmet><title>Dirigentes por Conjunto | Secretaria</title></Helmet><div className="flex-1 space-y-5">
 <div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-xl border" style={{borderColor:'hsl(var(--neon-igreja)/.25)',background:'hsl(var(--neon-igreja)/.10)'}}><Crown className="h-6 w-6" style={{color:GOLD}}/></div><div><h2 className="text-2xl font-bold md:text-3xl" style={{color:GOLD}}>Dirigentes por Conjunto</h2><p className="text-sm text-muted-foreground">Consulte os dirigentes responsáveis por cada conjunto.</p></div></div><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={()=>setFiltros(v=>!v)} className="border-[hsl(var(--neon-igreja)/.40)]"><Filter className="mr-2 h-4 w-4" style={{color:GOLD}}/>{filtros?'Ocultar Filtros':'Filtros'}{filtros?<ChevronUp/>:<ChevronDown/>}</Button><Button variant="outline" size="sm" onClick={excel} className="border-[hsl(var(--neon-igreja)/.40)]"><Download className="mr-2 h-4 w-4"/>Excel</Button><Button variant="outline" size="sm" onClick={pdf} className="border-[hsl(var(--neon-igreja)/.40)]"><FileText className="mr-2 h-4 w-4"/>PDF</Button><Button size="sm" onClick={imprimir} style={{background:GOLD,color:'#111827'}}><Printer className="mr-2 h-4 w-4"/>Imprimir</Button></div></div>
 <AnimatePresence>{filtros&&<motion.div initial={{height:0,opacity:0}} animate={{height:'auto'}} exit={{height:0,opacity:0}} className="overflow-hidden"><Card><CardHeader><CardTitle><Filter className="mr-2 inline h-4 w-4" style={{color:GOLD}}/>Filtros</CardTitle></CardHeader><CardContent className="grid gap-3 pt-0 md:grid-cols-3"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar dirigente ou conjunto..." className="pl-9"/></div><Select value={status} onValueChange={setStatus}><SelectTrigger><SelectValue placeholder="Status"/></SelectTrigger><SelectContent className="dark-igreja"><SelectItem value="todos">Todos</SelectItem><SelectItem value="ATIVO">Ativos</SelectItem><SelectItem value="INATIVO">Inativos</SelectItem></SelectContent></Select><Select value={conjunto} onValueChange={setConjunto}><SelectTrigger><SelectValue placeholder="Conjunto"/></SelectTrigger><SelectContent className="dark-igreja"><SelectItem value="todos">Todos</SelectItem>{conjuntos.map(c=><SelectItem key={c.id} value={String(c.id)}>{c.nome_conjunto}</SelectItem>)}</SelectContent></Select></CardContent></Card></motion.div>}</AnimatePresence>
 <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[['Dirigentes',people.length,Crown,GOLD],['Conjuntos',grouped.length,Users,GOLD],['Vínculos',vinculos,Shield,'#a855f7'],['Ativos',ativos,Users,'#22c55e']].map(([a,b,I,c])=><Card key={a}><CardContent className="p-4"><div className="flex items-center justify-between"><div><p className="text-xs uppercase text-muted-foreground">{a}</p><p className="mt-1 text-2xl font-bold" style={{color:c}}>{b}</p></div><I className="h-5 w-5" style={{color:c}}/></div></CardContent></Card>)}</div>
 {loading?<div className="py-16 text-center"><div className="mx-auto h-9 w-9 animate-spin rounded-full border-4 border-primary border-t-transparent"/><p className="mt-3 text-sm text-muted-foreground">Carregando...</p></div>:<div className="grid grid-cols-1 gap-5 md:grid-cols-2 xl:grid-cols-3">{grouped.map(c=><motion.div key={c.id} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}}><Card><CardHeader className="border-b"><CardTitle className="flex items-center justify-between"><span className="truncate"><Crown className="mr-2 inline h-4 w-4" style={{color:GOLD}}/>{c.nome_conjunto}</span><Badge variant="outline" style={{color:GOLD,borderColor:'hsl(var(--neon-igreja)/.30)'}}>{c.dirigentes.length}</Badge></CardTitle></CardHeader><CardContent className="space-y-2 p-0">{c.dirigentes.map(m=><button key={m.id} onClick={()=>setSelected(m)} className="flex w-full items-center gap-3 border-b border-border px-4 py-3 text-left hover:bg-muted/20"><div className="flex h-9 w-9 items-center justify-center rounded-full border" style={{borderColor:'hsl(var(--neon-igreja)/.30)',color:GOLD}}>{ini(m.nome_completo)}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{m.nome_completo}</p><p className="truncate text-xs text-muted-foreground">{m.cargo?.nome_cargo||funcs(m,funcoes)}</p></div><Badge variant="outline">{m.status||'ATIVO'}</Badge></button>)}</CardContent></Card></motion.div>)}</div>}
 </div>
 <Dialog open={!!selected} onOpenChange={v=>!v&&setSelected(null)}><DialogContent><DialogHeader><DialogTitle style={{color:GOLD}}><Crown className="mr-2 inline"/>Ficha do Dirigente</DialogTitle></DialogHeader>{selected&&<div className="grid grid-cols-1 gap-3 sm:grid-cols-2">{[['Nome Completo',selected.nome_completo],['Conjuntos',dirIds(selected).map(id=>conjuntos.find(c=>String(c.id)===String(id))?.nome_conjunto).filter(Boolean).join(', ')||'-'],['Cargo',selected.cargo?.nome_cargo||'-'],['Função/Funções',funcs(selected,funcoes)],['Classe da EBD',selected.igreja_classes?.nome_classe||'-'],['Status',selected.status||'ATIVO']].map(([a,b])=><div className="rounded-lg border p-3" key={a}><span className="block text-[10px] uppercase text-muted-foreground">{a}</span><b>{b}</b></div>)}</div>}<DialogFooter><Button variant="outline" onClick={()=>setSelected(null)}><X className="mr-2 h-4 w-4"/>Fechar</Button></DialogFooter></DialogContent></Dialog>
 </div>
}
