import React,{useState,useEffect,useCallback,useMemo}from'react';
import{motion,AnimatePresence}from'framer-motion';
import{Users,Music,Download,FileText,Printer,UserMinus,Layers,Search,Filter,ChevronDown,ChevronUp}from'lucide-react';
import{supabase}from'@/lib/customSupabaseClient';
import{useToast}from'@/components/ui/use-toast';
import{Card,CardHeader,CardTitle,CardContent}from'@/components/ui/card';
import{Button}from'@/components/ui/button';
import{Input}from'@/components/ui/input';
import{Badge}from'@/components/ui/badge';
import{Select,SelectContent,SelectItem,SelectTrigger,SelectValue}from'@/components/ui/select';
import{ScrollArea}from'@/components/ui/scroll-area';
import{exportToExcel}from'@/lib/ExportUtils';
import{Helmet}from'react-helmet';
import jsPDF from'jspdf';
import autoTable from'jspdf-autotable';

const GOLD='hsl(var(--neon-igreja))';
const LOGO='https://horizons-cdn.hostinger.com/23ae9372-1ce3-488a-9be5-00d3fa6b6d54/20edc9a8be1c027e0ddf5f8071ef876e.png';

export default function ConsultaMembrosConjunto(){
 const{toast}=useToast();
 const[all,setAll]=useState([]),[conjuntos,setConjuntos]=useState([]),[loading,setLoading]=useState(true),[status,setStatus]=useState('ATIVO'),[conjunto,setConjunto]=useState('todos'),[search,setSearch]=useState(''),[filtros,setFiltros]=useState(true);

 const load=useCallback(async()=>{setLoading(true);try{const[a,b]=await Promise.all([supabase.from('igreja_conjuntos').select('*').order('nome_conjunto',{ascending:true}),supabase.from('igreja_membros').select('id,nome_completo,conjunto_id,participa_conjunto,status,cargo:cargos_igreja(nome_cargo)').order('nome_completo',{ascending:true})]);if(a.error)throw a.error;if(b.error)throw b.error;setConjuntos(a.data||[]);setAll(b.data||[])}catch(e){toast({title:'Erro ao buscar dados',description:e.message,variant:'destructive'})}finally{setLoading(false)}},[toast]);
 useEffect(()=>{load()},[load]);

 const filtered=useMemo(()=>{const t=search.trim().toLowerCase();return all.filter(m=>(status==='todos'||(m.status||'ATIVO')===status)&&(conjunto==='todos'||String(m.conjunto_id)===String(conjunto))&&(!t||(m.nome_completo||'').toLowerCase().includes(t)))},[all,status,conjunto,search]);
 const grouped=useMemo(()=>{const l=conjuntos.map(c=>({...c,membros:filtered.filter(m=>m.participa_conjunto===true&&String(m.conjunto_id)===String(c.id)),sem:false}));const s=filtered.filter(m=>m.participa_conjunto===false||!m.conjunto_id);if(s.length&&conjunto==='todos')l.push({id:'sem',nome_conjunto:'SEM CONJUNTO',membros:s,sem:true});return l},[conjuntos,filtered,conjunto]);
 const ativos=filtered.filter(m=>(m.status||'ATIVO')==='ATIVO').length,inativos=filtered.length-ativos,grupos=grouped.filter(c=>c.membros.length&&!c.sem).length,sem=grouped.find(c=>c.sem)?.membros.length||0;

 const excel=()=>{const rows=grouped.flatMap(c=>c.membros.map(m=>({Conjunto:c.nome_conjunto,Membro:m.nome_completo,Cargo:m.cargo?.nome_cargo||'-',Status:m.status||'ATIVO'})));if(!rows.length)return toast({title:'Nenhum dado',description:'Não há membros para exportar.',variant:'destructive'});exportToExcel(rows,'Membros_por_Conjunto','Membros')};
 const pdf=()=>{if(!filtered.length)return toast({title:'Nenhum dado',description:'Não há membros.',variant:'destructive'});const d=new jsPDF('p','mm','a4');d.setFont('helvetica','bold');d.setTextColor(30,58,138);d.setFontSize(12);d.text('IGREJA ASSEMBLEIA DE DEUS MINISTÉRIO PLANTAR',105,12,{align:'center'});d.setFontSize(8);d.text('LEROLÂNDIA',105,18,{align:'center'});d.setFillColor(30,58,138);d.roundedRect(10,25,190,8,2,2,'F');d.setTextColor(255,255,255);d.setFontSize(7);d.text('RELATÓRIO DE MEMBROS POR CONJUNTO',105,30,{align:'center'});let y=40;grouped.forEach(c=>{if(y>255){d.addPage();y=18}d.setFillColor(c.sem?[255,247,237]:[239,246,255]);d.roundedRect(10,y,190,8,2,2,'F');d.setTextColor(c.sem?[180,83,9]:[30,58,138]);d.text(c.nome_conjunto,14,y+5.5);d.text(String(c.membros.length),196,y+5.5,{align:'right'});y+=10;if(c.membros.length){autoTable(d,{head:[['MEMBRO','CARGO','STATUS']],body:c.membros.map(m=>[m.nome_completo||'-',m.cargo?.nome_cargo||'-',m.status||'ATIVO']),startY:y,theme:'grid',styles:{fontSize:7,cellPadding:2},headStyles:{fillColor:[37,99,235]}});y=(d.lastAutoTable?.finalY||y)+6}else y+=8});d.save('Membros_por_Conjunto.pdf')};
 const imprimir=()=>{if(!filtered.length)return toast({title:'Nenhum dado',description:'Não há membros.',variant:'destructive'});const w=window.open('','_blank');if(!w)return toast({title:'Impressão bloqueada',description:'Permita pop-ups.',variant:'destructive'});w.document.write(`<html><head><title>Membros por Conjunto</title><style>body{font-family:Arial;margin:20px}h1{text-align:center}h2{background:#eab308;padding:7px;text-align:center}.g{margin:10px 0}.gh{background:#0f172a;color:#fff;padding:6px;font-weight:bold}table{width:100%;border-collapse:collapse;font-size:9px}th{background:#2563eb;color:#fff}th,td{border:1px solid #ccc;padding:5px}</style></head><body><h1>IGREJA ASSEMBLEIA DE DEUS MINISTÉRIO PLANTAR</h1><h2>MEMBROS POR CONJUNTO</h2>${grouped.map(c=>`<div class="g"><div class="gh">${c.nome_conjunto} (${c.membros.length})</div><table><tr><th>MEMBRO</th><th>CARGO</th><th>STATUS</th></tr>${c.membros.map(m=>`<tr><td>${m.nome_completo||'-'}</td><td>${m.cargo?.nome_cargo||'-'}</td><td>${m.status||'ATIVO'}</td></tr>`).join('')}</table></div>`).join('')}<script>window.onload=()=>setTimeout(()=>window.print(),150)<\/script></body></html>`);w.document.close()};

 return <div className="dark-igreja text-foreground h-full flex flex-col"><Helmet><title>Membros por Conjunto | Secretaria</title></Helmet><div className="flex-1 space-y-5">
  <div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-xl border" style={{borderColor:'hsl(var(--neon-igreja)/.25)',background:'hsl(var(--neon-igreja)/.10)'}}><Music className="h-6 w-6" style={{color:GOLD}}/></div><div><h2 className="text-2xl font-bold md:text-3xl" style={{color:GOLD}}>Membros por Conjunto</h2><p className="text-sm text-muted-foreground">Distribuição dos membros entre os conjuntos da igreja.</p></div></div><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={()=>setFiltros(v=>!v)} className="border-[hsl(var(--neon-igreja)/.40)]"><Filter className="mr-2 h-4 w-4" style={{color:GOLD}}/>{filtros?'Ocultar Filtros':'Filtros'}{filtros?<ChevronUp/>:<ChevronDown/>}</Button><Button variant="outline" size="sm" onClick={excel} className="border-[hsl(var(--neon-igreja)/.40)]"><Download className="mr-2 h-4 w-4"/>Excel</Button><Button variant="outline" size="sm" onClick={pdf} className="border-[hsl(var(--neon-igreja)/.40)]"><FileText className="mr-2 h-4 w-4"/>PDF</Button><Button size="sm" onClick={imprimir} style={{background:GOLD,color:'#111827'}}><Printer className="mr-2 h-4 w-4"/>Imprimir</Button></div></div>

  <AnimatePresence>{filtros&&<motion.div initial={{height:0}} animate={{height:'auto'}} exit={{height:0}} className="overflow-hidden"><Card><CardHeader className="border-b"><CardTitle><Filter className="mr-2 inline h-4 w-4" style={{color:GOLD}}/>Filtros</CardTitle></CardHeader><CardContent className="grid gap-3 pt-4 md:grid-cols-3"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar membro..." className="pl-9"/></div><Select value={status} onValueChange={setStatus}><SelectTrigger><SelectValue placeholder="Status"/></SelectTrigger><SelectContent className="dark-igreja"><SelectItem value="todos">Todos</SelectItem><SelectItem value="ATIVO">Ativos</SelectItem><SelectItem value="INATIVO">Inativos</SelectItem></SelectContent></Select><Select value={conjunto} onValueChange={setConjunto}><SelectTrigger><SelectValue placeholder="Conjunto"/></SelectTrigger><SelectContent className="dark-igreja"><SelectItem value="todos">Todos os Conjuntos</SelectItem>{conjuntos.map(c=><SelectItem key={c.id} value={String(c.id)}>{c.nome_conjunto}</SelectItem>)}</SelectContent></Select></CardContent></Card></motion.div>}</AnimatePresence>

  <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[['Membros',filtered.length,Users,GOLD],['Conjuntos',conjuntos.length,Layers,GOLD],['Ativos',ativos,Users,'#22c55e'],['Inativos',inativos,UserMinus,'#ef4444']].map(([a,b,I,c])=><Card key={a}><CardContent className="p-4"><div className="flex items-center justify-between"><div><p className="text-xs uppercase text-muted-foreground">{a}</p><p className="mt-1 text-2xl font-bold" style={{color:c}}>{b}</p></div><I className="h-5 w-5" style={{color:c}}/></div></CardContent></Card>)}</div>

  {loading?<div className="py-16 text-center"><div className="mx-auto h-9 w-9 animate-spin rounded-full border-4 border-primary border-t-transparent"/><p className="mt-3 text-sm text-muted-foreground">Carregando conjuntos...</p></div>:!grouped.length?<div className="rounded-xl border border-dashed p-16 text-center"><Music className="mx-auto h-12 w-12 text-muted-foreground/50"/><h3 className="mt-3 font-bold">Nenhum conjunto encontrado</h3></div>:<div className="grid grid-cols-1 gap-5 md:grid-cols-2 xl:grid-cols-3">{grouped.map(c=><motion.div key={c.id} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}}><Card className={`overflow-hidden ${c.sem?'border-amber-500/30':'hover:border-[hsl(var(--neon-igreja)/.50)]'}`}><CardHeader className="border-b"><CardTitle className="flex items-center justify-between"><span className="flex min-w-0 items-center gap-2 truncate">{c.sem?<UserMinus className="h-4 w-4 text-amber-500"/>:<Music className="h-4 w-4" style={{color:GOLD}}/>}<span className="truncate">{c.nome_conjunto}</span></span><Badge variant="outline" style={{color:c.sem?'#f59e0b':GOLD,borderColor:c.sem?'#f59e0b':'hsl(var(--neon-igreja)/.30)'}}>{c.membros.length}</Badge></CardTitle></CardHeader><CardContent className="p-0">{!c.membros.length?<div className="py-10 text-center text-sm text-muted-foreground">Nenhum membro vinculado.</div>:<ScrollArea className="h-[300px]"><div className="divide-y">{c.membros.map((m,i)=><div key={m.id} className="flex items-center gap-3 px-4 py-3 hover:bg-muted/20"><div className={`flex h-9 w-9 items-center justify-center rounded-full border text-xs font-bold ${(m.status||'ATIVO')==='INATIVO'?'border-red-500/30 text-red-500':''}`} style={(m.status||'ATIVO')==='ATIVO'?{borderColor:'hsl(var(--neon-igreja)/.30)',color:GOLD}:undefined}>{i+1}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{m.nome_completo}</p><p className="truncate text-[10px] text-muted-foreground">{m.cargo?.nome_cargo||'Sem cargo'}</p></div>{(m.status||'ATIVO')==='INATIVO'?<Badge variant="destructive">INATIVO</Badge>:<Users className="h-4 w-4 text-muted-foreground"/>}</div>)}</div></ScrollArea>}</CardContent></Card></motion.div>)}</div>}
 </div>
 </div>
}
